const colorsCoreBlueBlue50 = "#e6edf7";
const colorsCoreBlueBlue100 = "#b0c6e6";
const colorsCoreBlueBlue200 = "#8aaad9";
const colorsCoreBlueBlue300 = "#5483c8";
const colorsCoreBlueBlue400 = "#0072ce";
const colorsCoreBlueBlue500 = "#0046ad";
const colorsCoreBlueBlue600 = "#00409d";
const colorsCoreBlueBlue700 = "#00327b";
const colorsCoreBlueBlue800 = "#00275f";
const colorsCoreBlueBlue900 = "#001d49";
const colorsCoreNeutralsBlack = "#000000";
const colorsCoreNeutralsWhite = "#ffffff";
const colorsCoreNeutralsTransparent = "#ffffff03";
const colorsCoreGreenGreen50 = "#e6f2eb";
const colorsCoreGreenGreen100 = "#b0d6c0";
const colorsCoreGreenGreen200 = "#8ac2a1";
const colorsCoreGreenGreen300 = "#54a676";
const colorsCoreGreenGreen400 = "#33955c";
const colorsCoreGreenGreen500 = "#007a33";
const colorsCoreGreenGreen600 = "#006f2e";
const colorsCoreGreenGreen700 = "#005724";
const colorsCoreGreenGreen800 = "#00431c";
const colorsCoreGreenGreen900 = "#003315";
const colorsCoreRedRed50 = "#f8e8eb";
const colorsCoreRedRed100 = "#e9b6c2";
const colorsCoreRedRed200 = "#de93a4";
const colorsCoreRedRed300 = "#cf627b";
const colorsCoreRedRed400 = "#c54461";
const colorsCoreRedRed500 = "#b7153a";
const colorsCoreRedRed600 = "#a71335";
const colorsCoreRedRed700 = "#820f29";
const colorsCoreRedRed800 = "#650c20";
const colorsCoreRedRed900 = "#4d0918";
const colorsCorePurple50 = "#faf5ff";
const colorsCorePurple100 = "#f3e8ff";
const colorsCorePurple200 = "#e9d5ff";
const colorsCorePurple300 = "#d8b4fe";
const colorsCorePurple400 = "#c084fc";
const colorsCorePurple500 = "#a855f7";
const colorsCorePurple600 = "#9333ea";
const colorsCorePurple700 = "#7e22ce";
const colorsCorePurple800 = "#6b21a8";
const colorsCorePurple900 = "#581c87";
const colorsCoreAmberAmber50 = "#fef6e6";
const colorsCoreAmberAmber100 = "#fbe4b0";
const colorsCoreAmberAmber200 = "#f9d78a";
const colorsCoreAmberAmber300 = "#f6c554";
const colorsCoreAmberAmber400 = "#f5ba33";
const colorsCoreAmberAmber500 = "#f2a900";
const colorsCoreAmberAmber600 = "#dc9a00";
const colorsCoreAmberAmber700 = "#ac7800";
const colorsCoreAmberAmber800 = "#855d00";
const colorsCoreAmberAmber900 = "#664700";
const colorsCoreGreyGrey50 = "#f0f0f0";
const colorsCoreGreyGrey100 = "#d0d0d0";
const colorsCoreGreyGrey200 = "#b9b9b9";
const colorsCoreGreyGrey300 = "#989898";
const colorsCoreGreyGrey400 = "#858585";
const colorsCoreGreyGrey500 = "#666666";
const colorsCoreGreyGrey600 = "#5d5d5d";
const colorsCoreGreyGrey700 = "#484848";
const colorsCoreGreyGrey800 = "#383838";
const colorsCoreGreyGrey900 = "#2b2b2b";
const colorsSemanticFgDefault = colorsCoreGreyGrey800;
const colorsSemanticFgMuted = colorsCoreGreyGrey500;
const colorsSemanticFgSubtle = colorsCoreGreyGrey300;
const colorsSemanticFgOnAccent = colorsCoreNeutralsWhite;
const colorsSemanticFgOnDisabled = colorsCoreGreyGrey300;
const colorsSemanticFgDisabled = colorsCoreGreyGrey50;
const colorsSemanticCtaDefault = colorsCoreBlueBlue400;
const colorsSemanticFgAccent = colorsSemanticCtaDefault;
const colorsSemanticBgSurface = colorsCoreNeutralsWhite;
const colorsSemanticBgMuted = colorsCoreGreyGrey500;
const colorsSemanticBgSubtle = colorsCoreGreyGrey100;
const colorsSemanticBgDisabled = colorsCoreGreyGrey50;
const colorsSemanticBgCanvas = colorsCoreBlueBlue50;
const colorsSemanticCtaEmphasised = colorsCoreBlueBlue500;
const colorsSemanticCtaMuted = colorsCoreBlueBlue300;
const colorsSemanticCtaSubtle = colorsCoreBlueBlue100;
const colorsSemanticCtaDisabled = colorsCoreGreyGrey300;
const colorsSemanticPrimaryDefault = colorsCoreBlueBlue400;
const colorsSemanticPrimaryEmphasised = colorsCoreBlueBlue500;
const colorsSemanticPrimaryMuted = colorsCoreBlueBlue300;
const colorsSemanticPrimarySubtle = colorsCoreBlueBlue100;
const colorsSemanticPrimaryDisabled = colorsCoreGreyGrey300;
const colorsSemanticSecondaryDefault = colorsCoreGreyGrey800;
const colorsSemanticSecondaryEmphasised = colorsCoreGreyGrey700;
const colorsSemanticSecondaryMuted = colorsCoreGreyGrey500;
const colorsSemanticSecondarySubtle = colorsCoreGreyGrey100;
const colorsSemanticSecondaryDisabled = colorsCoreGreyGrey300;
const colorsSemanticWarningFg = colorsCoreAmberAmber500;
const colorsSemanticWarningEmphasised = colorsCoreAmberAmber600;
const colorsSemanticWarningMuted = colorsCoreAmberAmber400;
const colorsSemanticWarningSubtle = colorsCoreAmberAmber100;
const colorsSemanticWarningOnWarning = colorsCoreGreyGrey800;
const colorsSemanticErrorFg = colorsCoreRedRed500;
const colorsSemanticErrorEmphasised = colorsCoreRedRed600;
const colorsSemanticErrorMuted = colorsCoreRedRed400;
const colorsSemanticErrorSubtle = colorsCoreRedRed100;
const colorsSemanticErrorOnError = colorsCoreNeutralsWhite;
const colorsSemanticInfoFg = colorsCoreBlueBlue500;
const colorsSemanticInfoEmphasised = colorsCoreBlueBlue600;
const colorsSemanticInfoMuted = colorsCoreBlueBlue400;
const colorsSemanticInfoSubtle = colorsCoreBlueBlue100;
const colorsSemanticInfoOnInfo = colorsCoreNeutralsWhite;
const colorsSemanticSuccessFg = colorsCoreGreenGreen500;
const colorsSemanticSuccessEmphasised = colorsCoreGreenGreen600;
const colorsSemanticSuccessMuted = colorsCoreGreenGreen400;
const colorsSemanticSuccessSubtle = colorsCoreGreenGreen100;
const colorsSemanticSuccessOnSuccess = colorsCoreNeutralsWhite;
const colorsSemanticHelpFg = colorsCorePurple500;
const colorsSemanticHelpEmphasised = colorsCorePurple600;
const colorsSemanticHelpMuted = colorsCorePurple400;
const colorsSemanticHelpSubtle = colorsCorePurple100;
const colorsSemanticHelpOnSuccess = colorsCoreNeutralsWhite;
const colorsSemanticNeutralFg = colorsCoreGreyGrey400;
const colorsSemanticNeutralEmphasised = colorsCoreGreyGrey500;
const colorsSemanticNeutralMuted = colorsCoreGreyGrey300;
const colorsSemanticNeutralSubtle = colorsCoreGreyGrey100;
const colorsSemanticNeutralOnSuccess = colorsCoreNeutralsWhite;
const colorsSemanticInputsBackground = colorsSemanticBgSurface;
const colorsSemanticInputsText = colorsSemanticFgMuted;
const colorsSemanticInputsPlaceholder = colorsSemanticFgSubtle;
const colorsSemanticInputsDefaultLabel = colorsSemanticNeutralFg;
const colorsSemanticInputsDefaultIconColor = colorsSemanticFgDefault;
const colorsSemanticBorderDefault = colorsSemanticBgSubtle;
const colorsSemanticInputsDefaultBorderColor = colorsSemanticBorderDefault;
const colorsSemanticTypographyDefault = colorsCoreGreyGrey800;
const colorsSemanticInputsDefaultTextColor = colorsSemanticTypographyDefault;
const colorsSemanticInputsDefaultBackgroundColor = colorsSemanticInputsBackground;
const colorsSemanticInputsSelectedBorderColor = colorsSemanticCtaDefault;
const colorsSemanticInputsSelectedTextColor = colorsSemanticCtaDefault;
const colorsSemanticInputsSelectedIconColor = colorsSemanticCtaDefault;
const colorsSemanticInputsSelectedHoverBorderColor = colorsSemanticCtaMuted;
const colorsSemanticInputsSelectedHoverTextColor = colorsSemanticCtaMuted;
const colorsSemanticInputsSelectedHoverIconColor = colorsSemanticCtaMuted;
const colorsSemanticInputsSelectedHoverBackgroundColor = colorsSemanticInputsBackground;
const colorsSemanticInputsSelectedBackgroundColor = colorsSemanticInputsBackground;
const colorsSemanticInputsErrorBorderColor = colorsSemanticErrorFg;
const colorsSemanticInputsErrorTextColor = colorsSemanticErrorFg;
const colorsSemanticInputsErrorIconColor = colorsSemanticErrorFg;
const colorsSemanticInputsErrorBackgroundColor = colorsSemanticInputsBackground;
const colorsSemanticInputsDisabledBackgroundColor = colorsSemanticBgDisabled;
const colorsSemanticInputsDisabledTextColor = colorsSemanticFgOnDisabled;
const colorsSemanticInputsDisabledIconColor = colorsSemanticFgOnDisabled;
const colorsSemanticInputsBorderDisabled = colorsSemanticFgOnDisabled;
const colorsSemanticInputsDisabledBorderColor = colorsSemanticInputsBorderDisabled;
const colorsSemanticInputsHoverBackgroundColor = colorsCoreNeutralsWhite;
const colorsSemanticInputsBorderDefault = colorsSemanticBgMuted;
const colorsSemanticInputsHoverBorderColor = colorsSemanticInputsBorderDefault;
const colorsSemanticInputsHoverTextColor = colorsSemanticInputsText;
const colorsSemanticInputsHoverIconColor = colorsSemanticInputsText;
const colorsSemanticInputsFocusBorderColor = colorsSemanticCtaDefault;
const colorsSemanticInputsFocusIconColor = colorsSemanticFgDefault;
const colorsSemanticInputsFocusFocusRing = colorsCoreBlueBlue50;
const colorsSemanticInputsFocusTextColor = colorsSemanticTypographyDefault;
const colorsSemanticInputsFocusBackgroundColor = colorsSemanticInputsBackground;
const colorsSemanticInputsFgDisabled = colorsSemanticFgDisabled;
const colorsSemanticInputsWarningBorderColor = colorsSemanticWarningFg;
const colorsSemanticInputsWarningTextColor = colorsSemanticWarningFg;
const colorsSemanticInputsWarningIconColor = colorsSemanticWarningFg;
const colorsSemanticInputsWarningBackgroundColor = colorsSemanticInputsBackground;
const colorsSemanticInputsSuccessBorderColor = colorsSemanticSuccessFg;
const colorsSemanticInputsSuccessTextColor = colorsSemanticSuccessFg;
const colorsSemanticInputsSuccessIconColor = colorsSemanticSuccessFg;
const colorsSemanticInputsSuccessBackgroundColor = colorsSemanticInputsBackground;
const colorsSemanticActionsNegativeDefaultBorderColor = colorsSemanticErrorFg;
const colorsSemanticActionsNegativeDefaultQuietBorderColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsNegativeDefaultTextColor = colorsSemanticErrorFg;
const colorsSemanticActionsNegativeDefaultQuietTextColor = colorsSemanticErrorFg;
const colorsSemanticActionsNegativeDefaultBackgroundColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsNegativeDefaultQuietBackgroundColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsNegativeHoverBorderColor = colorsSemanticErrorMuted;
const colorsSemanticActionsNegativeHoverQuietBorderColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsNegativeHoverTextColor = colorsCoreNeutralsWhite;
const colorsSemanticActionsNegativeHoverQuietTextColor = colorsSemanticErrorMuted;
const colorsSemanticActionsNegativeHoverBackgroundColor = colorsSemanticErrorMuted;
const colorsSemanticActionsNegativeHoverQuietBackgroundColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsNegativeActiveBorderColor = colorsSemanticErrorEmphasised;
const colorsSemanticActionsNegativeActiveQuietBorderColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsNegativeActiveTextColor = colorsCoreNeutralsWhite;
const colorsSemanticActionsNegativeActiveQuietTextColor = colorsSemanticErrorEmphasised;
const colorsSemanticActionsNegativeActiveBackgroundColor = colorsSemanticErrorEmphasised;
const colorsSemanticActionsNegativeActiveQuietBackgroundColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsNegativeFocusBorderColor = colorsSemanticErrorFg;
const colorsSemanticActionsNegativeFocusQuietBorderColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsNegativeFocusTextColor = colorsSemanticErrorFg;
const colorsSemanticActionsNegativeFocusQuietTextColor = colorsSemanticErrorFg;
const colorsSemanticActionsNegativeFocusBackgroundColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsNegativeFocusQuietBackgroundColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsCtaDefaultBorderColor = colorsSemanticCtaDefault;
const colorsSemanticActionsCtaDefaultTextColor = colorsCoreNeutralsWhite;
const colorsSemanticActionsCtaDefaultBackgroundColor = colorsSemanticCtaDefault;
const colorsSemanticActionsCtaHoverBorderColor = colorsSemanticCtaEmphasised;
const colorsSemanticActionsCtaHoverTextColor = colorsCoreNeutralsWhite;
const colorsSemanticActionsCtaHoverBackgroundColor = colorsSemanticCtaEmphasised;
const colorsSemanticActionsCtaActiveBorderColor = colorsSemanticCtaEmphasised;
const colorsSemanticActionsCtaActiveTextColor = colorsCoreNeutralsWhite;
const colorsSemanticActionsCtaActiveBackgroundColor = colorsSemanticCtaEmphasised;
const colorsSemanticActionsCtaFocusBorderColor = colorsSemanticActionsCtaHoverBorderColor;
const colorsSemanticActionsCtaFocusTextColor = colorsCoreNeutralsWhite;
const colorsSemanticActionsCtaFocusBackgroundColor = colorsSemanticCtaDefault;
const colorsSemanticActionsPrimaryDefaultBorderColor = colorsSemanticPrimaryDefault;
const colorsSemanticActionsPrimaryDefaultQuietBorderColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsPrimaryDefaultTextColor = colorsSemanticPrimaryDefault;
const colorsSemanticActionsPrimaryDefaultQuietTextColor = colorsSemanticPrimaryDefault;
const colorsSemanticActionsPrimaryDefaultBackgroundColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsPrimaryDefaultQuietBackgroundColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsPrimaryHoverBorderColor = colorsSemanticPrimaryMuted;
const colorsSemanticActionsPrimaryHoverQuietBorderColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsPrimaryHoverTextColor = colorsCoreNeutralsWhite;
const colorsSemanticActionsPrimaryHoverQuietTextColor = colorsCoreNeutralsWhite;
const colorsSemanticActionsPrimaryHoverBackgroundColor = colorsSemanticPrimaryMuted;
const colorsSemanticActionsPrimaryHoverQuietBackgroundColor = colorsSemanticPrimaryMuted;
const colorsSemanticActionsPrimaryActiveBorderColor = colorsSemanticPrimaryEmphasised;
const colorsSemanticActionsPrimaryActiveQuietBorderColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsPrimaryActiveTextColor = colorsCoreNeutralsWhite;
const colorsSemanticActionsPrimaryActiveQuietTextColor = colorsCoreNeutralsWhite;
const colorsSemanticActionsPrimaryActiveBackgroundColor = colorsSemanticPrimaryEmphasised;
const colorsSemanticActionsPrimaryActiveQuietBackgroundColor = colorsSemanticPrimaryEmphasised;
const colorsSemanticActionsPrimaryFocusBorderColor = colorsSemanticPrimaryDefault;
const colorsSemanticActionsPrimaryFocusQuietBorderColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsPrimaryFocusTextColor = colorsSemanticPrimaryDefault;
const colorsSemanticActionsPrimaryFocusQuietTextColor = colorsSemanticPrimaryDefault;
const colorsSemanticActionsPrimaryFocusBackgroundColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsPrimaryFocusQuietBackgroundColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsSecondaryDefaultBorderColor = colorsSemanticSecondaryDefault;
const colorsSemanticActionsSecondaryDefaultQuietBorderColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsSecondaryDefaultTextColor = colorsSemanticSecondaryDefault;
const colorsSemanticActionsSecondaryDefaultQuietTextColor = colorsSemanticSecondaryDefault;
const colorsSemanticActionsSecondaryDefaultBackgroundColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsSecondaryDefaultQuietBackgroundColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsSecondaryHoverBorderColor = colorsSemanticSecondaryMuted;
const colorsSemanticActionsSecondaryHoverQuietBorderColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsSecondaryHoverTextColor = colorsSemanticSecondaryDefault;
const colorsSemanticActionsSecondaryHoverQuietTextColor = colorsSemanticSecondaryDefault;
const colorsSemanticActionsSecondaryHoverBackgroundColor = colorsSemanticSecondaryMuted;
const colorsSemanticActionsSecondaryHoverQuietBackgroundColor = colorsSemanticSecondaryMuted;
const colorsSemanticActionsSecondaryActiveBorderColor = colorsSemanticSecondaryEmphasised;
const colorsSemanticActionsSecondaryActiveQuietBorderColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsSecondaryActiveTextColor = colorsCoreNeutralsWhite;
const colorsSemanticActionsSecondaryActiveQuietTextColor = colorsCoreNeutralsWhite;
const colorsSemanticActionsSecondaryActiveBackgroundColor = colorsSemanticSecondaryEmphasised;
const colorsSemanticActionsSecondaryActiveQuietBackgroundColor = colorsSemanticSecondaryEmphasised;
const colorsSemanticActionsSecondaryFocusBorderColor = colorsSemanticSecondaryDefault;
const colorsSemanticActionsSecondaryFocusQuietBorderColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsSecondaryFocusTextColor = colorsSemanticSecondaryDefault;
const colorsSemanticActionsSecondaryFocusQuietTextColor = colorsSemanticSecondaryDefault;
const colorsSemanticActionsSecondaryFocusBackgroundColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsSecondaryFocusQuietBackgroundColor = colorsCoreNeutralsTransparent;
const colorsSemanticActionsDisabledBackgroundColor = colorsSemanticFgDisabled;
const colorsSemanticActionsDisabledTextColor = colorsSemanticFgOnDisabled;
const colorsSemanticActionsDisabledBorderColor = colorsSemanticFgDisabled;
const colorsSemanticFeedbackInfoBorderColor = colorsSemanticInfoFg;
const colorsSemanticFeedbackInfoTextColor = colorsSemanticInfoFg;
const colorsSemanticFeedbackInfoIconColor = colorsSemanticInfoFg;
const colorsSemanticFeedbackInfoBackgroundColor = colorsSemanticInfoSubtle;
const colorsSemanticFeedbackWarningBorderColor = colorsSemanticWarningFg;
const colorsSemanticFeedbackWarningTextColor = colorsSemanticWarningFg;
const colorsSemanticFeedbackWarningIconColor = colorsSemanticWarningFg;
const colorsSemanticFeedbackWarningBackgroundColor = colorsSemanticWarningSubtle;
const colorsSemanticFeedbackSuccessBorderColor = colorsSemanticSuccessFg;
const colorsSemanticFeedbackSuccessTextColor = colorsSemanticSuccessFg;
const colorsSemanticFeedbackSuccessIconColor = colorsSemanticSuccessFg;
const colorsSemanticFeedbackSuccessBackgroundColor = colorsSemanticSuccessSubtle;
const colorsSemanticFeedbackHelpBorderColor = colorsSemanticHelpFg;
const colorsSemanticFeedbackHelpTextColor = colorsSemanticHelpFg;
const colorsSemanticFeedbackHelpIconColor = colorsSemanticHelpFg;
const colorsSemanticFeedbackHelpBackgroundColor = colorsSemanticHelpSubtle;
const colorsSemanticFeedbackNeutralBorderColor = colorsSemanticNeutralFg;
const colorsSemanticFeedbackNeutralTextColor = colorsSemanticNeutralFg;
const colorsSemanticFeedbackNeutralIconColor = colorsSemanticNeutralFg;
const colorsSemanticFeedbackNeutralBackgroundColor = colorsSemanticNeutralSubtle;
const colorsSemanticFeedbackErrorBorderColor = colorsSemanticErrorFg;
const colorsSemanticFeedbackErrorTextColor = colorsSemanticErrorFg;
const colorsSemanticFeedbackErrorIconColor = colorsSemanticErrorFg;
const colorsSemanticFeedbackErrorBackgroundColor = colorsSemanticErrorSubtle;
const colorsSemanticTypographyOnBackground = colorsCoreNeutralsWhite;
const colorsSemanticStatusInfoBorderColor = colorsSemanticInfoFg;
const colorsSemanticStatusInfoTextColor = colorsSemanticInfoFg;
const colorsSemanticStatusInfoIconColor = colorsSemanticInfoFg;
const colorsSemanticStatusInfoBackgroundColor = colorsSemanticInfoSubtle;
const colorsSemanticStatusWarningBorderColor = colorsSemanticWarningFg;
const colorsSemanticStatusWarningTextColor = colorsSemanticWarningFg;
const colorsSemanticStatusWarningIconColor = colorsSemanticWarningFg;
const colorsSemanticStatusWarningBackgroundColor = colorsSemanticWarningSubtle;
const colorsSemanticStatusSuccessBorderColor = colorsSemanticSuccessFg;
const colorsSemanticStatusSuccessTextColor = colorsSemanticSuccessFg;
const colorsSemanticStatusSuccessIconColor = colorsSemanticSuccessFg;
const colorsSemanticStatusSuccessBackgroundColor = colorsSemanticSuccessSubtle;
const colorsSemanticStatusHelpBorderColor = colorsSemanticHelpFg;
const colorsSemanticStatusHelpTextColor = colorsSemanticHelpFg;
const colorsSemanticStatusHelpIconColor = colorsSemanticHelpFg;
const colorsSemanticStatusHelpBackgroundColor = colorsSemanticHelpSubtle;
const colorsSemanticStatusNeutralBorderColor = colorsSemanticNeutralFg;
const colorsSemanticStatusNeutralTextColor = colorsSemanticNeutralFg;
const colorsSemanticStatusNeutralIconColor = colorsSemanticNeutralFg;
const colorsSemanticStatusNeutralBackgroundColor = colorsSemanticNeutralSubtle;
const colorsSemanticStatusErrorBorderColor = colorsSemanticErrorFg;
const colorsSemanticStatusErrorTextColor = colorsSemanticErrorFg;
const colorsSemanticStatusErrorIconColor = colorsSemanticErrorFg;
const colorsSemanticStatusErrorBackgroundColor = colorsSemanticErrorSubtle;
const colorsSemanticContainerDefault = colorsCoreGreyGrey500;
const colorsSemanticContainerOnBackground = colorsCoreNeutralsWhite;
const colorsSemanticNavigationBackgroundColor = colorsSemanticCtaDefault;
const colorsSemanticNavigationBorderColor = colorsSemanticCtaEmphasised;
const colorsSemanticNavigationFontColor = colorsSemanticFgOnAccent;
const colorsSemanticNavigationIconColor = colorsSemanticFgOnAccent;
const colorsSemanticFocusBorderColor = colorsSemanticCtaSubtle;
const colorsCompButtonCtaDefaultBackgroundColor = colorsSemanticActionsCtaDefaultBackgroundColor;
const colorsCompButtonCtaDefaultTextColor = colorsSemanticActionsCtaDefaultTextColor;
const colorsCompButtonCtaDefaultBorderColor = colorsSemanticActionsCtaDefaultBorderColor;
const colorsCompButtonCtaDefaultIconColor = colorsSemanticActionsCtaDefaultTextColor;
const colorsCompButtonCtaHoverBackgroundColor = colorsSemanticActionsCtaHoverBackgroundColor;
const colorsCompButtonCtaHoverTextColor = colorsSemanticActionsCtaHoverTextColor;
const colorsCompButtonCtaHoverBorderColor = colorsSemanticActionsCtaHoverBorderColor;
const colorsCompButtonCtaHoverIconColor = colorsSemanticActionsCtaHoverTextColor;
const colorsCompButtonCtaActiveBackgroundColor = colorsSemanticActionsCtaActiveBackgroundColor;
const colorsCompButtonCtaActiveTextColor = colorsSemanticActionsCtaActiveTextColor;
const colorsCompButtonCtaActiveBorderColor = colorsSemanticActionsCtaActiveBorderColor;
const colorsCompButtonCtaActiveIconColor = colorsSemanticActionsCtaActiveTextColor;
const colorsCompButtonCtaFocusBackgroundColor = colorsSemanticActionsCtaFocusBackgroundColor;
const colorsCompButtonCtaFocusTextColor = colorsSemanticActionsCtaFocusTextColor;
const colorsCompButtonCtaFocusBorderColor = colorsSemanticActionsCtaFocusBorderColor;
const colorsCompButtonCtaFocusIconColor = colorsSemanticActionsCtaFocusTextColor;
const colorsCompButtonPrimaryDefaultBackgroundColor = colorsSemanticActionsPrimaryDefaultBackgroundColor;
const colorsCompButtonPrimaryDefaultQuietBackgroundColor = colorsSemanticActionsPrimaryDefaultQuietBackgroundColor;
const colorsCompButtonPrimaryDefaultTextColor = colorsSemanticActionsPrimaryDefaultTextColor;
const colorsCompButtonPrimaryDefaultQuietTextColor = colorsSemanticActionsPrimaryDefaultQuietTextColor;
const colorsCompButtonPrimaryDefaultBorderColor = colorsSemanticActionsPrimaryDefaultBorderColor;
const colorsCompButtonPrimaryDefaultQuietBorderColor = colorsSemanticActionsPrimaryDefaultQuietBorderColor;
const colorsCompButtonPrimaryDefaultIconColor = colorsSemanticActionsPrimaryDefaultTextColor;
const colorsCompButtonPrimaryDefaultQuietIconColor = colorsSemanticActionsPrimaryDefaultQuietTextColor;
const colorsCompButtonPrimaryHoverBackgroundColor = colorsSemanticActionsPrimaryHoverBackgroundColor;
const colorsCompButtonPrimaryHoverQuietBackgroundColor = colorsSemanticActionsPrimaryHoverQuietBackgroundColor;
const colorsCompButtonPrimaryHoverTextColor = colorsSemanticActionsPrimaryHoverTextColor;
const colorsCompButtonPrimaryHoverQuietTextColor = colorsSemanticActionsPrimaryHoverQuietTextColor;
const colorsCompButtonPrimaryHoverBorderColor = colorsSemanticActionsPrimaryHoverBorderColor;
const colorsCompButtonPrimaryHoverQuietBorderColor = colorsSemanticActionsPrimaryHoverQuietBorderColor;
const colorsCompButtonPrimaryHoverIconColor = colorsSemanticActionsPrimaryHoverTextColor;
const colorsCompButtonPrimaryHoverQuietIconColor = colorsSemanticActionsPrimaryHoverQuietTextColor;
const colorsCompButtonPrimaryActiveBackgroundColor = colorsSemanticActionsPrimaryActiveBackgroundColor;
const colorsCompButtonPrimaryActiveQuietBackgroundColor = colorsSemanticActionsPrimaryActiveQuietBackgroundColor;
const colorsCompButtonPrimaryActiveTextColor = colorsSemanticActionsPrimaryActiveTextColor;
const colorsCompButtonPrimaryActiveQuietTextColor = colorsSemanticActionsPrimaryActiveQuietTextColor;
const colorsCompButtonPrimaryActiveBorderColor = colorsSemanticActionsPrimaryActiveBorderColor;
const colorsCompButtonPrimaryActiveQuietBorderColor = colorsSemanticActionsPrimaryActiveQuietBorderColor;
const colorsCompButtonPrimaryActiveIconColor = colorsSemanticActionsPrimaryActiveTextColor;
const colorsCompButtonPrimaryActiveQuietIconColor = colorsSemanticActionsPrimaryActiveQuietTextColor;
const colorsCompButtonPrimaryFocusBackgroundColor = colorsSemanticActionsPrimaryFocusBackgroundColor;
const colorsCompButtonPrimaryFocusQuietBackgroundColor = colorsSemanticActionsPrimaryFocusQuietBackgroundColor;
const colorsCompButtonPrimaryFocusTextColor = colorsSemanticActionsPrimaryFocusTextColor;
const colorsCompButtonPrimaryFocusQuietTextColor = colorsSemanticActionsPrimaryFocusQuietTextColor;
const colorsCompButtonPrimaryFocusBorderColor = colorsSemanticActionsPrimaryFocusBorderColor;
const colorsCompButtonPrimaryFocusQuietBorderColor = colorsSemanticActionsPrimaryFocusQuietBorderColor;
const colorsCompButtonPrimaryFocusIconColor = colorsSemanticActionsPrimaryFocusTextColor;
const colorsCompButtonPrimaryFocusQuietIconColor = colorsSemanticActionsPrimaryFocusQuietTextColor;
const colorsCompButtonSecondaryDefaultBackgroundColor = colorsSemanticActionsSecondaryDefaultBackgroundColor;
const colorsCompButtonSecondaryDefaultQuietBackgroundColor = colorsSemanticActionsSecondaryDefaultQuietBackgroundColor;
const colorsCompButtonSecondaryDefaultTextColor = colorsSemanticActionsSecondaryDefaultTextColor;
const colorsCompButtonSecondaryDefaultQuietTextColor = colorsSemanticActionsSecondaryDefaultQuietTextColor;
const colorsCompButtonSecondaryDefaultBorderColor = colorsSemanticActionsSecondaryDefaultBorderColor;
const colorsCompButtonSecondaryDefaultQuietBorderColor = colorsSemanticActionsSecondaryDefaultQuietBorderColor;
const colorsCompButtonSecondaryDefaultIconColor = colorsSemanticActionsSecondaryDefaultTextColor;
const colorsCompButtonSecondaryDefaultQuietIconColor = colorsSemanticActionsSecondaryDefaultQuietTextColor;
const colorsCompButtonSecondaryHoverBackgroundColor = colorsSemanticActionsSecondaryHoverBackgroundColor;
const colorsCompButtonSecondaryHoverQuietBackgroundColor = colorsSemanticActionsSecondaryHoverQuietBackgroundColor;
const colorsCompButtonSecondaryHoverTextColor = colorsSemanticActionsSecondaryHoverTextColor;
const colorsCompButtonSecondaryHoverQuietTextColor = colorsSemanticActionsSecondaryHoverQuietTextColor;
const colorsCompButtonSecondaryHoverBorderColor = colorsSemanticActionsSecondaryHoverBorderColor;
const colorsCompButtonSecondaryHoverQuietBorderColor = colorsSemanticActionsSecondaryHoverQuietBorderColor;
const colorsCompButtonSecondaryHoverIconColor = colorsSemanticActionsSecondaryHoverTextColor;
const colorsCompButtonSecondaryHoverQuietIconColor = colorsSemanticActionsSecondaryHoverQuietTextColor;
const colorsCompButtonSecondaryActiveBackgroundColor = colorsSemanticActionsSecondaryActiveBackgroundColor;
const colorsCompButtonSecondaryActiveQuietBackgroundColor = colorsSemanticActionsSecondaryActiveQuietBackgroundColor;
const colorsCompButtonSecondaryActiveTextColor = colorsSemanticActionsSecondaryActiveTextColor;
const colorsCompButtonSecondaryActiveQuietTextColor = colorsSemanticActionsSecondaryActiveQuietTextColor;
const colorsCompButtonSecondaryActiveBorderColor = colorsSemanticActionsSecondaryActiveBorderColor;
const colorsCompButtonSecondaryActiveQuietBorderColor = colorsSemanticActionsSecondaryActiveQuietBorderColor;
const colorsCompButtonSecondaryActiveIconColor = colorsSemanticActionsSecondaryActiveTextColor;
const colorsCompButtonSecondaryActiveQuietIconColor = colorsSemanticActionsSecondaryActiveQuietTextColor;
const colorsCompButtonSecondaryFocusBackgroundColor = colorsSemanticActionsSecondaryFocusBackgroundColor;
const colorsCompButtonSecondaryFocusQuietBackgroundColor = colorsSemanticActionsSecondaryFocusQuietBackgroundColor;
const colorsCompButtonSecondaryFocusTextColor = colorsSemanticActionsSecondaryFocusTextColor;
const colorsCompButtonSecondaryFocusQuietTextColor = colorsSemanticActionsSecondaryFocusQuietTextColor;
const colorsCompButtonSecondaryFocusBorderColor = colorsSemanticActionsSecondaryFocusBorderColor;
const colorsCompButtonSecondaryFocusQuietBorderColor = colorsSemanticActionsSecondaryFocusQuietBorderColor;
const colorsCompButtonSecondaryFocusIconColor = colorsSemanticActionsSecondaryFocusTextColor;
const colorsCompButtonSecondaryFocusQuietIconColor = colorsSemanticActionsSecondaryFocusQuietTextColor;
const colorsCompButtonNegativeDefaultBackgroundColor = colorsSemanticActionsNegativeDefaultBackgroundColor;
const colorsCompButtonNegativeDefaultQuietBackgroundColor = colorsSemanticActionsNegativeDefaultBackgroundColor;
const colorsCompButtonNegativeDefaultTextColor = colorsSemanticActionsNegativeDefaultTextColor;
const colorsCompButtonNegativeDefaultQuietTextColor = colorsSemanticActionsNegativeDefaultQuietTextColor;
const colorsCompButtonNegativeDefaultBorderColor = colorsSemanticActionsNegativeDefaultBorderColor;
const colorsCompButtonNegativeDefaultQuietBorderColor = colorsSemanticActionsNegativeDefaultQuietBorderColor;
const colorsCompButtonNegativeDefaultIconColor = colorsSemanticActionsNegativeDefaultTextColor;
const colorsCompButtonNegativeDefaultQuietIconColor = colorsSemanticActionsNegativeDefaultQuietTextColor;
const colorsCompButtonNegativeHoverBackgroundColor = colorsSemanticActionsNegativeHoverBackgroundColor;
const colorsCompButtonNegativeHoverQuietBackgroundColor = colorsSemanticActionsNegativeHoverQuietBackgroundColor;
const colorsCompButtonNegativeHoverTextColor = colorsSemanticActionsNegativeHoverTextColor;
const colorsCompButtonNegativeHoverQuietTextColor = colorsSemanticActionsNegativeHoverQuietTextColor;
const colorsCompButtonNegativeHoverBorderColor = colorsSemanticActionsNegativeHoverBorderColor;
const colorsCompButtonNegativeHoverQuietBorderColor = colorsSemanticActionsNegativeHoverQuietBorderColor;
const colorsCompButtonNegativeHoverIconColor = colorsSemanticActionsNegativeHoverTextColor;
const colorsCompButtonNegativeHoverQuietIconColor = colorsSemanticActionsNegativeHoverQuietTextColor;
const colorsCompButtonNegativeActiveBackgroundColor = colorsSemanticActionsNegativeActiveBackgroundColor;
const colorsCompButtonNegativeActiveQuietBackgroundColor = colorsSemanticActionsNegativeActiveQuietBackgroundColor;
const colorsCompButtonNegativeActiveTextColor = colorsSemanticActionsNegativeActiveTextColor;
const colorsCompButtonNegativeActiveQuietTextColor = colorsSemanticActionsNegativeActiveQuietTextColor;
const colorsCompButtonNegativeActiveBorderColor = colorsSemanticActionsNegativeActiveBorderColor;
const colorsCompButtonNegativeActiveQuietBorderColor = colorsSemanticActionsNegativeActiveQuietBorderColor;
const colorsCompButtonNegativeActiveIconColor = colorsSemanticActionsNegativeActiveTextColor;
const colorsCompButtonNegativeActiveQuietIconColor = colorsSemanticActionsNegativeActiveQuietTextColor;
const colorsCompButtonNegativeFocusBackgroundColor = colorsSemanticActionsNegativeFocusBackgroundColor;
const colorsCompButtonNegativeFocusQuietBackgroundColor = colorsSemanticActionsNegativeFocusQuietBackgroundColor;
const colorsCompButtonNegativeFocusTextColor = colorsSemanticActionsNegativeFocusTextColor;
const colorsCompButtonNegativeFocusQuietTextColor = colorsSemanticActionsNegativeFocusQuietTextColor;
const colorsCompButtonNegativeFocusBorderColor = colorsSemanticActionsNegativeFocusBorderColor;
const colorsCompButtonNegativeFocusQuietBorderColor = colorsSemanticActionsNegativeFocusQuietBorderColor;
const colorsCompButtonNegativeFocusIconColor = colorsSemanticActionsNegativeFocusTextColor;
const colorsCompButtonNegativeFocusQuietIconColor = colorsSemanticActionsNegativeFocusQuietTextColor;
const colorsCompButtonDisabledBackgroundColor = colorsSemanticActionsDisabledBackgroundColor;
const colorsCompButtonDisabledTextColor = colorsSemanticActionsDisabledTextColor;
const colorsCompButtonDisabledBorderColor = colorsSemanticActionsDisabledBackgroundColor;
const colorsCompButtonDisabledIconColor = colorsSemanticActionsDisabledTextColor;
const colorsCompFormsInputsTextPlaceholder = colorsSemanticInputsPlaceholder;
const colorsCompFormsInputsIconDefault = colorsSemanticInputsDefaultIconColor;
const colorsCompFormsInputsLabel = colorsSemanticFgMuted;
const colorsCompFormsInputsBorderDefault = colorsSemanticInputsBorderDefault;
const colorsCompFormsInputsBorderDisabled = colorsSemanticInputsBorderDisabled;
const colorsCompFormsInputsBorderReadOnly = colorsSemanticInputsBorderDisabled;
const colorsCompFormsInputsBorderFocus = colorsSemanticInputsFocusBorderColor;
const colorsCompFormsInputsBorderError = colorsSemanticInputsErrorBorderColor;
const colorsCompFormsInputsBorderSuccess = colorsSemanticInputsSuccessBorderColor;
const colorsCompFormsInputsBorderWarning = colorsSemanticInputsWarningBorderColor;
const colorsCompFormsInputsBackgroundDisabled = colorsSemanticInputsDisabledBackgroundColor;
const colorsCompFormsInputsBackgroundReadOnly = colorsSemanticInputsDisabledBackgroundColor;
const colorsCompFormsInputsTextDisabled = colorsSemanticInputsDisabledTextColor;
const colorsCompFormsInputsIconDisabled = colorsSemanticInputsDisabledIconColor;
const colorsCompFormsInputsIconError = colorsSemanticInputsErrorIconColor;
const colorsCompFormsInputsIconSuccess = colorsSemanticInputsSuccessIconColor;
const colorsCompFormsInputsIconWarning = colorsSemanticInputsWarningIconColor;
const colorsCompFormsInputsTextDefault = colorsSemanticInputsDefaultTextColor;
const colorsCompFormsInputsBackground = colorsSemanticInputsDefaultBackgroundColor;
const colorsCompAccordionBg = colorsSemanticBgSurface;
const colorsCompAccordionTextDefault = colorsSemanticTypographyDefault;
const colorsCompAccordionIcon = colorsSemanticTypographyDefault;
const colorsCompAccordionTitle = colorsSemanticPrimaryDefault;
const colorsCompAccordionIconDefault = colorsSemanticPrimaryDefault;
const colorsCompAccordionIconHover = colorsSemanticCtaEmphasised;
const colorsCompAccordionTitleDefault = colorsSemanticTypographyDefault;
const colorsCompAccordionTitleHover = colorsSemanticCtaEmphasised;
const colorsCompAccordionBorderOpen = colorsSemanticPrimaryDefault;
const colorsSemanticInputsBorderSubtle = colorsSemanticNeutralSubtle;
const colorsCompAccordionBorderDefault = colorsSemanticInputsBorderSubtle;

export const Colors = {
    colorsCoreBlueBlue50,
    colorsCoreBlueBlue100,
    colorsCoreBlueBlue200,
    colorsCoreBlueBlue300,
    colorsCoreBlueBlue400,
    colorsCoreBlueBlue500,
    colorsCoreBlueBlue600,
    colorsCoreBlueBlue700,
    colorsCoreBlueBlue800,
    colorsCoreBlueBlue900,
    colorsCoreNeutralsBlack,
    colorsCoreNeutralsWhite,
    colorsCoreNeutralsTransparent,
    colorsCoreGreenGreen50,
    colorsCoreGreenGreen100,
    colorsCoreGreenGreen200,
    colorsCoreGreenGreen300,
    colorsCoreGreenGreen400,
    colorsCoreGreenGreen500,
    colorsCoreGreenGreen600,
    colorsCoreGreenGreen700,
    colorsCoreGreenGreen800,
    colorsCoreGreenGreen900,
    colorsCoreRedRed50,
    colorsCoreRedRed100,
    colorsCoreRedRed200,
    colorsCoreRedRed300,
    colorsCoreRedRed400,
    colorsCoreRedRed500,
    colorsCoreRedRed600,
    colorsCoreRedRed700,
    colorsCoreRedRed800,
    colorsCoreRedRed900,
    colorsCorePurple50,
    colorsCorePurple100,
    colorsCorePurple200,
    colorsCorePurple300,
    colorsCorePurple400,
    colorsCorePurple500,
    colorsCorePurple600,
    colorsCorePurple700,
    colorsCorePurple800,
    colorsCorePurple900,
    colorsCoreAmberAmber50,
    colorsCoreAmberAmber100,
    colorsCoreAmberAmber200,
    colorsCoreAmberAmber300,
    colorsCoreAmberAmber400,
    colorsCoreAmberAmber500,
    colorsCoreAmberAmber600,
    colorsCoreAmberAmber700,
    colorsCoreAmberAmber800,
    colorsCoreAmberAmber900,
    colorsCoreGreyGrey50,
    colorsCoreGreyGrey100,
    colorsCoreGreyGrey200,
    colorsCoreGreyGrey300,
    colorsCoreGreyGrey400,
    colorsCoreGreyGrey500,
    colorsCoreGreyGrey600,
    colorsCoreGreyGrey700,
    colorsCoreGreyGrey800,
    colorsCoreGreyGrey900,
    colorsSemanticFgDefault,
    colorsSemanticFgMuted,
    colorsSemanticFgSubtle,
    colorsSemanticFgOnAccent,
    colorsSemanticFgOnDisabled,
    colorsSemanticFgDisabled,
    colorsSemanticCtaDefault,
    colorsSemanticFgAccent,
    colorsSemanticBgSurface,
    colorsSemanticBgMuted,
    colorsSemanticBgSubtle,
    colorsSemanticBgDisabled,
    colorsSemanticBgCanvas,
    colorsSemanticCtaEmphasised,
    colorsSemanticCtaMuted,
    colorsSemanticCtaSubtle,
    colorsSemanticCtaDisabled,
    colorsSemanticPrimaryDefault,
    colorsSemanticPrimaryEmphasised,
    colorsSemanticPrimaryMuted,
    colorsSemanticPrimarySubtle,
    colorsSemanticPrimaryDisabled,
    colorsSemanticSecondaryDefault,
    colorsSemanticSecondaryEmphasised,
    colorsSemanticSecondaryMuted,
    colorsSemanticSecondarySubtle,
    colorsSemanticSecondaryDisabled,
    colorsSemanticWarningFg,
    colorsSemanticWarningEmphasised,
    colorsSemanticWarningMuted,
    colorsSemanticWarningSubtle,
    colorsSemanticWarningOnWarning,
    colorsSemanticErrorFg,
    colorsSemanticErrorEmphasised,
    colorsSemanticErrorMuted,
    colorsSemanticErrorSubtle,
    colorsSemanticErrorOnError,
    colorsSemanticInfoFg,
    colorsSemanticInfoEmphasised,
    colorsSemanticInfoMuted,
    colorsSemanticInfoSubtle,
    colorsSemanticInfoOnInfo,
    colorsSemanticSuccessFg,
    colorsSemanticSuccessEmphasised,
    colorsSemanticSuccessMuted,
    colorsSemanticSuccessSubtle,
    colorsSemanticSuccessOnSuccess,
    colorsSemanticHelpFg,
    colorsSemanticHelpEmphasised,
    colorsSemanticHelpMuted,
    colorsSemanticHelpSubtle,
    colorsSemanticHelpOnSuccess,
    colorsSemanticNeutralFg,
    colorsSemanticNeutralEmphasised,
    colorsSemanticNeutralMuted,
    colorsSemanticNeutralSubtle,
    colorsSemanticNeutralOnSuccess,
    colorsSemanticInputsBackground,
    colorsSemanticInputsText,
    colorsSemanticInputsPlaceholder,
    colorsSemanticInputsDefaultLabel,
    colorsSemanticInputsDefaultIconColor,
    colorsSemanticBorderDefault,
    colorsSemanticInputsDefaultBorderColor,
    colorsSemanticTypographyDefault,
    colorsSemanticInputsDefaultTextColor,
    colorsSemanticInputsDefaultBackgroundColor,
    colorsSemanticInputsSelectedBorderColor,
    colorsSemanticInputsSelectedTextColor,
    colorsSemanticInputsSelectedIconColor,
    colorsSemanticInputsSelectedHoverBorderColor,
    colorsSemanticInputsSelectedHoverTextColor,
    colorsSemanticInputsSelectedHoverIconColor,
    colorsSemanticInputsSelectedHoverBackgroundColor,
    colorsSemanticInputsSelectedBackgroundColor,
    colorsSemanticInputsErrorBorderColor,
    colorsSemanticInputsErrorTextColor,
    colorsSemanticInputsErrorIconColor,
    colorsSemanticInputsErrorBackgroundColor,
    colorsSemanticInputsDisabledBackgroundColor,
    colorsSemanticInputsDisabledTextColor,
    colorsSemanticInputsDisabledIconColor,
    colorsSemanticInputsBorderDisabled,
    colorsSemanticInputsDisabledBorderColor,
    colorsSemanticInputsHoverBackgroundColor,
    colorsSemanticInputsBorderDefault,
    colorsSemanticInputsHoverBorderColor,
    colorsSemanticInputsHoverTextColor,
    colorsSemanticInputsHoverIconColor,
    colorsSemanticInputsFocusBorderColor,
    colorsSemanticInputsFocusIconColor,
    colorsSemanticInputsFocusFocusRing,
    colorsSemanticInputsFocusTextColor,
    colorsSemanticInputsFocusBackgroundColor,
    colorsSemanticInputsFgDisabled,
    colorsSemanticInputsWarningBorderColor,
    colorsSemanticInputsWarningTextColor,
    colorsSemanticInputsWarningIconColor,
    colorsSemanticInputsWarningBackgroundColor,
    colorsSemanticInputsSuccessBorderColor,
    colorsSemanticInputsSuccessTextColor,
    colorsSemanticInputsSuccessIconColor,
    colorsSemanticInputsSuccessBackgroundColor,
    colorsSemanticActionsNegativeDefaultBorderColor,
    colorsSemanticActionsNegativeDefaultQuietBorderColor,
    colorsSemanticActionsNegativeDefaultTextColor,
    colorsSemanticActionsNegativeDefaultQuietTextColor,
    colorsSemanticActionsNegativeDefaultBackgroundColor,
    colorsSemanticActionsNegativeDefaultQuietBackgroundColor,
    colorsSemanticActionsNegativeHoverBorderColor,
    colorsSemanticActionsNegativeHoverQuietBorderColor,
    colorsSemanticActionsNegativeHoverTextColor,
    colorsSemanticActionsNegativeHoverQuietTextColor,
    colorsSemanticActionsNegativeHoverBackgroundColor,
    colorsSemanticActionsNegativeHoverQuietBackgroundColor,
    colorsSemanticActionsNegativeActiveBorderColor,
    colorsSemanticActionsNegativeActiveQuietBorderColor,
    colorsSemanticActionsNegativeActiveTextColor,
    colorsSemanticActionsNegativeActiveQuietTextColor,
    colorsSemanticActionsNegativeActiveBackgroundColor,
    colorsSemanticActionsNegativeActiveQuietBackgroundColor,
    colorsSemanticActionsNegativeFocusBorderColor,
    colorsSemanticActionsNegativeFocusQuietBorderColor,
    colorsSemanticActionsNegativeFocusTextColor,
    colorsSemanticActionsNegativeFocusQuietTextColor,
    colorsSemanticActionsNegativeFocusBackgroundColor,
    colorsSemanticActionsNegativeFocusQuietBackgroundColor,
    colorsSemanticActionsCtaDefaultBorderColor,
    colorsSemanticActionsCtaDefaultTextColor,
    colorsSemanticActionsCtaDefaultBackgroundColor,
    colorsSemanticActionsCtaHoverBorderColor,
    colorsSemanticActionsCtaHoverTextColor,
    colorsSemanticActionsCtaHoverBackgroundColor,
    colorsSemanticActionsCtaActiveBorderColor,
    colorsSemanticActionsCtaActiveTextColor,
    colorsSemanticActionsCtaActiveBackgroundColor,
    colorsSemanticActionsCtaFocusBorderColor,
    colorsSemanticActionsCtaFocusTextColor,
    colorsSemanticActionsCtaFocusBackgroundColor,
    colorsSemanticActionsPrimaryDefaultBorderColor,
    colorsSemanticActionsPrimaryDefaultQuietBorderColor,
    colorsSemanticActionsPrimaryDefaultTextColor,
    colorsSemanticActionsPrimaryDefaultQuietTextColor,
    colorsSemanticActionsPrimaryDefaultBackgroundColor,
    colorsSemanticActionsPrimaryDefaultQuietBackgroundColor,
    colorsSemanticActionsPrimaryHoverBorderColor,
    colorsSemanticActionsPrimaryHoverQuietBorderColor,
    colorsSemanticActionsPrimaryHoverTextColor,
    colorsSemanticActionsPrimaryHoverQuietTextColor,
    colorsSemanticActionsPrimaryHoverBackgroundColor,
    colorsSemanticActionsPrimaryHoverQuietBackgroundColor,
    colorsSemanticActionsPrimaryActiveBorderColor,
    colorsSemanticActionsPrimaryActiveQuietBorderColor,
    colorsSemanticActionsPrimaryActiveTextColor,
    colorsSemanticActionsPrimaryActiveQuietTextColor,
    colorsSemanticActionsPrimaryActiveBackgroundColor,
    colorsSemanticActionsPrimaryActiveQuietBackgroundColor,
    colorsSemanticActionsPrimaryFocusBorderColor,
    colorsSemanticActionsPrimaryFocusQuietBorderColor,
    colorsSemanticActionsPrimaryFocusTextColor,
    colorsSemanticActionsPrimaryFocusQuietTextColor,
    colorsSemanticActionsPrimaryFocusBackgroundColor,
    colorsSemanticActionsPrimaryFocusQuietBackgroundColor,
    colorsSemanticActionsSecondaryDefaultBorderColor,
    colorsSemanticActionsSecondaryDefaultQuietBorderColor,
    colorsSemanticActionsSecondaryDefaultTextColor,
    colorsSemanticActionsSecondaryDefaultQuietTextColor,
    colorsSemanticActionsSecondaryDefaultBackgroundColor,
    colorsSemanticActionsSecondaryDefaultQuietBackgroundColor,
    colorsSemanticActionsSecondaryHoverBorderColor,
    colorsSemanticActionsSecondaryHoverQuietBorderColor,
    colorsSemanticActionsSecondaryHoverTextColor,
    colorsSemanticActionsSecondaryHoverQuietTextColor,
    colorsSemanticActionsSecondaryHoverBackgroundColor,
    colorsSemanticActionsSecondaryHoverQuietBackgroundColor,
    colorsSemanticActionsSecondaryActiveBorderColor,
    colorsSemanticActionsSecondaryActiveQuietBorderColor,
    colorsSemanticActionsSecondaryActiveTextColor,
    colorsSemanticActionsSecondaryActiveQuietTextColor,
    colorsSemanticActionsSecondaryActiveBackgroundColor,
    colorsSemanticActionsSecondaryActiveQuietBackgroundColor,
    colorsSemanticActionsSecondaryFocusBorderColor,
    colorsSemanticActionsSecondaryFocusQuietBorderColor,
    colorsSemanticActionsSecondaryFocusTextColor,
    colorsSemanticActionsSecondaryFocusQuietTextColor,
    colorsSemanticActionsSecondaryFocusBackgroundColor,
    colorsSemanticActionsSecondaryFocusQuietBackgroundColor,
    colorsSemanticActionsDisabledBackgroundColor,
    colorsSemanticActionsDisabledTextColor,
    colorsSemanticActionsDisabledBorderColor,
    colorsSemanticFeedbackInfoBorderColor,
    colorsSemanticFeedbackInfoTextColor,
    colorsSemanticFeedbackInfoIconColor,
    colorsSemanticFeedbackInfoBackgroundColor,
    colorsSemanticFeedbackWarningBorderColor,
    colorsSemanticFeedbackWarningTextColor,
    colorsSemanticFeedbackWarningIconColor,
    colorsSemanticFeedbackWarningBackgroundColor,
    colorsSemanticFeedbackSuccessBorderColor,
    colorsSemanticFeedbackSuccessTextColor,
    colorsSemanticFeedbackSuccessIconColor,
    colorsSemanticFeedbackSuccessBackgroundColor,
    colorsSemanticFeedbackHelpBorderColor,
    colorsSemanticFeedbackHelpTextColor,
    colorsSemanticFeedbackHelpIconColor,
    colorsSemanticFeedbackHelpBackgroundColor,
    colorsSemanticFeedbackNeutralBorderColor,
    colorsSemanticFeedbackNeutralTextColor,
    colorsSemanticFeedbackNeutralIconColor,
    colorsSemanticFeedbackNeutralBackgroundColor,
    colorsSemanticFeedbackErrorBorderColor,
    colorsSemanticFeedbackErrorTextColor,
    colorsSemanticFeedbackErrorIconColor,
    colorsSemanticFeedbackErrorBackgroundColor,
    colorsSemanticTypographyOnBackground,
    colorsSemanticStatusInfoBorderColor,
    colorsSemanticStatusInfoTextColor,
    colorsSemanticStatusInfoIconColor,
    colorsSemanticStatusInfoBackgroundColor,
    colorsSemanticStatusWarningBorderColor,
    colorsSemanticStatusWarningTextColor,
    colorsSemanticStatusWarningIconColor,
    colorsSemanticStatusWarningBackgroundColor,
    colorsSemanticStatusSuccessBorderColor,
    colorsSemanticStatusSuccessTextColor,
    colorsSemanticStatusSuccessIconColor,
    colorsSemanticStatusSuccessBackgroundColor,
    colorsSemanticStatusHelpBorderColor,
    colorsSemanticStatusHelpTextColor,
    colorsSemanticStatusHelpIconColor,
    colorsSemanticStatusHelpBackgroundColor,
    colorsSemanticStatusNeutralBorderColor,
    colorsSemanticStatusNeutralTextColor,
    colorsSemanticStatusNeutralIconColor,
    colorsSemanticStatusNeutralBackgroundColor,
    colorsSemanticStatusErrorBorderColor,
    colorsSemanticStatusErrorTextColor,
    colorsSemanticStatusErrorIconColor,
    colorsSemanticStatusErrorBackgroundColor,
    colorsSemanticContainerDefault,
    colorsSemanticContainerOnBackground,
    colorsSemanticNavigationBackgroundColor,
    colorsSemanticNavigationBorderColor,
    colorsSemanticNavigationFontColor,
    colorsSemanticNavigationIconColor,
    colorsSemanticFocusBorderColor,
    colorsCompButtonCtaDefaultBackgroundColor,
    colorsCompButtonCtaDefaultTextColor,
    colorsCompButtonCtaDefaultBorderColor,
    colorsCompButtonCtaDefaultIconColor,
    colorsCompButtonCtaHoverBackgroundColor,
    colorsCompButtonCtaHoverTextColor,
    colorsCompButtonCtaHoverBorderColor,
    colorsCompButtonCtaHoverIconColor,
    colorsCompButtonCtaActiveBackgroundColor,
    colorsCompButtonCtaActiveTextColor,
    colorsCompButtonCtaActiveBorderColor,
    colorsCompButtonCtaActiveIconColor,
    colorsCompButtonCtaFocusBackgroundColor,
    colorsCompButtonCtaFocusTextColor,
    colorsCompButtonCtaFocusBorderColor,
    colorsCompButtonCtaFocusIconColor,
    colorsCompButtonPrimaryDefaultBackgroundColor,
    colorsCompButtonPrimaryDefaultQuietBackgroundColor,
    colorsCompButtonPrimaryDefaultTextColor,
    colorsCompButtonPrimaryDefaultQuietTextColor,
    colorsCompButtonPrimaryDefaultBorderColor,
    colorsCompButtonPrimaryDefaultQuietBorderColor,
    colorsCompButtonPrimaryDefaultIconColor,
    colorsCompButtonPrimaryDefaultQuietIconColor,
    colorsCompButtonPrimaryHoverBackgroundColor,
    colorsCompButtonPrimaryHoverQuietBackgroundColor,
    colorsCompButtonPrimaryHoverTextColor,
    colorsCompButtonPrimaryHoverQuietTextColor,
    colorsCompButtonPrimaryHoverBorderColor,
    colorsCompButtonPrimaryHoverQuietBorderColor,
    colorsCompButtonPrimaryHoverIconColor,
    colorsCompButtonPrimaryHoverQuietIconColor,
    colorsCompButtonPrimaryActiveBackgroundColor,
    colorsCompButtonPrimaryActiveQuietBackgroundColor,
    colorsCompButtonPrimaryActiveTextColor,
    colorsCompButtonPrimaryActiveQuietTextColor,
    colorsCompButtonPrimaryActiveBorderColor,
    colorsCompButtonPrimaryActiveQuietBorderColor,
    colorsCompButtonPrimaryActiveIconColor,
    colorsCompButtonPrimaryActiveQuietIconColor,
    colorsCompButtonPrimaryFocusBackgroundColor,
    colorsCompButtonPrimaryFocusQuietBackgroundColor,
    colorsCompButtonPrimaryFocusTextColor,
    colorsCompButtonPrimaryFocusQuietTextColor,
    colorsCompButtonPrimaryFocusBorderColor,
    colorsCompButtonPrimaryFocusQuietBorderColor,
    colorsCompButtonPrimaryFocusIconColor,
    colorsCompButtonPrimaryFocusQuietIconColor,
    colorsCompButtonSecondaryDefaultBackgroundColor,
    colorsCompButtonSecondaryDefaultQuietBackgroundColor,
    colorsCompButtonSecondaryDefaultTextColor,
    colorsCompButtonSecondaryDefaultQuietTextColor,
    colorsCompButtonSecondaryDefaultBorderColor,
    colorsCompButtonSecondaryDefaultQuietBorderColor,
    colorsCompButtonSecondaryDefaultIconColor,
    colorsCompButtonSecondaryDefaultQuietIconColor,
    colorsCompButtonSecondaryHoverBackgroundColor,
    colorsCompButtonSecondaryHoverQuietBackgroundColor,
    colorsCompButtonSecondaryHoverTextColor,
    colorsCompButtonSecondaryHoverQuietTextColor,
    colorsCompButtonSecondaryHoverBorderColor,
    colorsCompButtonSecondaryHoverQuietBorderColor,
    colorsCompButtonSecondaryHoverIconColor,
    colorsCompButtonSecondaryHoverQuietIconColor,
    colorsCompButtonSecondaryActiveBackgroundColor,
    colorsCompButtonSecondaryActiveQuietBackgroundColor,
    colorsCompButtonSecondaryActiveTextColor,
    colorsCompButtonSecondaryActiveQuietTextColor,
    colorsCompButtonSecondaryActiveBorderColor,
    colorsCompButtonSecondaryActiveQuietBorderColor,
    colorsCompButtonSecondaryActiveIconColor,
    colorsCompButtonSecondaryActiveQuietIconColor,
    colorsCompButtonSecondaryFocusBackgroundColor,
    colorsCompButtonSecondaryFocusQuietBackgroundColor,
    colorsCompButtonSecondaryFocusTextColor,
    colorsCompButtonSecondaryFocusQuietTextColor,
    colorsCompButtonSecondaryFocusBorderColor,
    colorsCompButtonSecondaryFocusQuietBorderColor,
    colorsCompButtonSecondaryFocusIconColor,
    colorsCompButtonSecondaryFocusQuietIconColor,
    colorsCompButtonNegativeDefaultBackgroundColor,
    colorsCompButtonNegativeDefaultQuietBackgroundColor,
    colorsCompButtonNegativeDefaultTextColor,
    colorsCompButtonNegativeDefaultQuietTextColor,
    colorsCompButtonNegativeDefaultBorderColor,
    colorsCompButtonNegativeDefaultQuietBorderColor,
    colorsCompButtonNegativeDefaultIconColor,
    colorsCompButtonNegativeDefaultQuietIconColor,
    colorsCompButtonNegativeHoverBackgroundColor,
    colorsCompButtonNegativeHoverQuietBackgroundColor,
    colorsCompButtonNegativeHoverTextColor,
    colorsCompButtonNegativeHoverQuietTextColor,
    colorsCompButtonNegativeHoverBorderColor,
    colorsCompButtonNegativeHoverQuietBorderColor,
    colorsCompButtonNegativeHoverIconColor,
    colorsCompButtonNegativeHoverQuietIconColor,
    colorsCompButtonNegativeActiveBackgroundColor,
    colorsCompButtonNegativeActiveQuietBackgroundColor,
    colorsCompButtonNegativeActiveTextColor,
    colorsCompButtonNegativeActiveQuietTextColor,
    colorsCompButtonNegativeActiveBorderColor,
    colorsCompButtonNegativeActiveQuietBorderColor,
    colorsCompButtonNegativeActiveIconColor,
    colorsCompButtonNegativeActiveQuietIconColor,
    colorsCompButtonNegativeFocusBackgroundColor,
    colorsCompButtonNegativeFocusQuietBackgroundColor,
    colorsCompButtonNegativeFocusTextColor,
    colorsCompButtonNegativeFocusQuietTextColor,
    colorsCompButtonNegativeFocusBorderColor,
    colorsCompButtonNegativeFocusQuietBorderColor,
    colorsCompButtonNegativeFocusIconColor,
    colorsCompButtonNegativeFocusQuietIconColor,
    colorsCompButtonDisabledBackgroundColor,
    colorsCompButtonDisabledTextColor,
    colorsCompButtonDisabledBorderColor,
    colorsCompButtonDisabledIconColor,
    colorsCompFormsInputsTextPlaceholder,
    colorsCompFormsInputsIconDefault,
    colorsCompFormsInputsLabel,
    colorsCompFormsInputsBorderDefault,
    colorsCompFormsInputsBorderDisabled,
    colorsCompFormsInputsBorderReadOnly,
    colorsCompFormsInputsBorderFocus,
    colorsCompFormsInputsBorderError,
    colorsCompFormsInputsBorderSuccess,
    colorsCompFormsInputsBorderWarning,
    colorsCompFormsInputsBackgroundDisabled,
    colorsCompFormsInputsBackgroundReadOnly,
    colorsCompFormsInputsTextDisabled,
    colorsCompFormsInputsIconDisabled,
    colorsCompFormsInputsIconError,
    colorsCompFormsInputsIconSuccess,
    colorsCompFormsInputsIconWarning,
    colorsCompFormsInputsTextDefault,
    colorsCompFormsInputsBackground,
    colorsCompAccordionBg,
    colorsCompAccordionTextDefault,
    colorsCompAccordionIcon,
    colorsCompAccordionTitle,
    colorsCompAccordionIconDefault,
    colorsCompAccordionIconHover,
    colorsCompAccordionTitleDefault,
    colorsCompAccordionTitleHover,
    colorsCompAccordionBorderOpen,
    colorsSemanticInputsBorderSubtle,
    colorsCompAccordionBorderDefault,
}