name: Supernova <> Figma Token sync
on:
  # Any branch you want
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync_tokens:
    runs-on: ubuntu-latest
    steps:
      # Check out repository under $GITHUB_WORKSPACE, so the CLI utility can read it
      - uses: actions/checkout@v3

      # Setup node to use with CLI. 14+ is required
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      
      # Install Supernova CLI
      - name: Install Supernova CLI dependency
        run: npm install --g @supernovaio/cli

      # Sync tokens
      - name: Synchronize tokens with Supernova 
        run: supernova sync-tokens \
        --apiKey=sn.R7nXuEmjaVu3Qu5sqXMflLkLo6vLWI2ECWbdI1q8sJ78iWmnlUMJ1dC6BN7bVMo2M2IxBWhupY569R4XvCyDNBM32NlITvbv \
        --designSystemId=20980 \
        --tokenDirPath="schae-ma/tuvsud-TICA-design-system/tokens" \
        --configFilePath="schae-ma/tuvsud-TICA-design-system/supernova.settings.json" \
